import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ShieldCheck, AlertTriangle, Eye, Lock, Scale, RefreshCw } from "lucide-react";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "Responsible AI — WorkMate AI" },
      {
        name: "description",
        content: "How WorkMate AI handles accuracy, bias, privacy, and human-in-the-loop review.",
      },
    ],
  }),
  component: AboutPage,
});

const PRINCIPLES = [
  {
    icon: AlertTriangle,
    title: "AI-generated content disclaimer",
    body: "Outputs from WorkMate AI are generated by large language models and may contain inaccuracies, omissions, or outdated information. Always review before use in professional environments.",
  },
  {
    icon: Eye,
    title: "Human review required",
    body: "Every generated email, summary, plan, and chat response is a first draft. A human should verify facts, names, deadlines, and tone before sending or acting on it.",
  },
  {
    icon: Scale,
    title: "Bias awareness",
    body: "AI models can reflect biases in their training data. Be especially careful when AI suggestions influence hiring, performance, or interpersonal decisions — use your own judgement.",
  },
  {
    icon: Lock,
    title: "Data privacy",
    body: "Inputs are sent to the AI gateway only to generate the requested output. Do not paste confidential, regulated, or personally identifiable information you are not authorized to share.",
  },
  {
    icon: RefreshCw,
    title: "Editable and regeneratable",
    body: "All outputs are editable, copyable, and can be regenerated. You stay in control of the final wording, prioritization, and decisions.",
  },
];

function AboutPage() {
  return (
    <AppShell>
      <div className="mb-6 flex items-start gap-3">
        <div className="h-11 w-11 rounded-xl bg-accent/15 text-accent flex items-center justify-center">
          <ShieldCheck className="h-5 w-5" />
        </div>
        <div>
          <h1 className="text-2xl font-semibold">About & Responsible AI</h1>
          <p className="text-sm text-muted-foreground">
            How WorkMate AI is designed for safe, useful workplace productivity.
          </p>
        </div>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>What WorkMate AI does</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
          <p>
            WorkMate AI is a productivity assistant for professionals. It helps you draft emails,
            summarize meetings, plan tasks, and answer everyday workplace questions through
            structured prompts and a conversational assistant.
          </p>
          <p>
            It is intended to accelerate routine knowledge work — not to replace human judgement
            on decisions that affect people, finances, or compliance.
          </p>
        </CardContent>
      </Card>

      <div className="grid md:grid-cols-2 gap-4 mb-6">
        {PRINCIPLES.map(({ icon: Icon, title, body }) => (
          <Card key={title}>
            <CardContent className="p-5">
              <div className="flex items-center gap-2 mb-2">
                <div className="h-8 w-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
                  <Icon className="h-4 w-4" />
                </div>
                <div className="font-medium">{title}</div>
              </div>
              <p className="text-sm text-muted-foreground">{body}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          AI-generated outputs may contain inaccuracies and should be reviewed before use in
          professional environments. WorkMate AI is provided as a productivity aid, not a
          substitute for professional, legal, financial, or HR advice.
        </CardContent>
      </Card>
    </AppShell>
  );
}
